name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz
      
    - name: Extract ngrok
      run: tar xvzf ngrok.tgz
      
    - name: Auth ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        
    - name: Setup SSH
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server
        sudo systemctl enable ssh
        sudo systemctl start ssh
        echo -e "P@ssw0rd!\nP@ssw0rd!" | sudo passwd "${USER}"
        # Ensure ssh is running and accessible
        sudo ufw allow ssh
        
    - name: Create Tunnel
      run: ./ngrok tcp 22 &
